### ISSUE TITLE
Upgrade kubernetes version 

### ISSUE THREAD

**Issue by trashadewan** [shini4i/kubeseal-auto#28]
I am using a newer version of kuberenetes and requesting upgrade on the kubernetes python client api from "23.3.0"  to "24.2.0" or even greater.

**Comment by shini4i** [comment]
Hello @trashadewan, I will bump the version in the following days.

Just for my understanding, are you hitting some kind of issues with the newer version of k8s on this client version?

**Comment by trashadewan** [comment]
Nope, We are planning to upgrade our version and this will cause collision with the binary.

**Comment by shini4i** [comment]
I see. Technically, there shouldn't be compatibility problems with any recent Kubernetes version as this project is using only the stable API endpoints.

Nonetheless, you can upgrade to version `v0.4.8`, which has Kubernetes client version `29.0.0`.

I will go ahead and close this issue. Feel free to reach out if you will experience any problems.
