### ISSUE TITLE
feat: support multi keys 

### ISSUE THREAD

**Issue by ebuildy** [shini4i/kubeseal-auto#3]
Context: we run 4 k8s clusters, with different kubeseal keys.

I would like to be able to generate severals kubeseal secrets in a single command.

**Comment by shini4i** [comment]
Hi @ebuildy,

I never had such a use case in mind, but technically I don't think it will be hard to implement.

Are you using one kubeconfig with multiple contexts, or are you using multiple kubeconfig files?

**Comment by shini4i** [comment]
I will go ahead and close this issue. Feel free to add more information if that is something you still want to be implemented.
